default_game = devtest
server_announce = false
enable_damage = true
creative_mode = false
mainmenu_last_selected_world = 1
selected_world_path = /root/Tirith/gramine-tdx/CI-Examples/graphics/minetest/luanti-5.6.1/bin/../worlds/world1
enable_shaders = true
enable_particles = true
enable_3d_clouds = true
maintab_LAST = local
fps_max = 5000
fps_max_unfocused = 5000
autosave_screensize = false
smooth_lighting = true
screen_w = 1920
screen_h = 1080

# threading
enable_mapgen_debug_info = false
server_map_save_interval = 0

# reduce background threads
active_block_range = 2
num_emerge_threads = 1
emergequeue_limit_total = 0
emergequeue_limit_diskonly = 0

# rendering / timing
fps_max = 5000
fps_max_unfocused = 5000

# disable async features
enable_particles = true
enable_sound = false

enable_dynamic_shadows = true
fsaa = 4
anisotropic_filter = true
mip_map = true
trilinear_filter = true
bilinear_filter = false
node_highlighting = box
leaves_style = fancy
enable_waving_plants = true
enable_waving_leaves = true
connected_glass = true
shadow_levels = 4
opaque_water = true
tone_mapping = true
enable_waving_water = true
fixed_map_seed = 9594414812599699125
static_spawnpoint = 0,5,0
time_speed = 0
sqlite_synchronous = 0
vsync = false
max_block_generate_distance = 1000
viewing_range = 200
performance_tradeoffs = false
show_technical_names = false
update_last_known = 5015000
menu_last_game = devtest
update_last_checked = disabled
shadow_map_color = true
shadow_map_max_distance = 210
shadow_filters = 2
shadow_map_texture_32bit = true
shadow_map_texture_size = 4096
texture_clean_transparent = true
