# Copyright © 2017-2019 Intel Corporation
# SPDX-License-Identifier: MIT

files_libiris = files(
  'i915/iris_batch.c',
  'i915/iris_batch.h',
  'i915/iris_bufmgr.c',
  'i915/iris_bufmgr.h',
  'i915/iris_kmd_backend.c',
  'xe/iris_batch.c',
  'xe/iris_batch.h',
  'xe/iris_bufmgr.c',
  'xe/iris_bufmgr.h',
  'xe/iris_kmd_backend.c',
  'driinfo_iris.h',
  'iris_batch.c',
  'iris_batch.h',
  'iris_binder.c',
  'iris_binder.h',
  'iris_blit.c',
  'iris_border_color.c',
  'iris_bufmgr.c',
  'iris_bufmgr.h',
  'iris_clear.c',
  'iris_context.c',
  'iris_context.h',
  'iris_draw.c',
  'iris_fence.c',
  'iris_fence.h',
  'iris_fine_fence.c',
  'iris_fine_fence.h',
  'iris_formats.c',
  'iris_genx_macros.h',
  'iris_genx_protos.h',
  'iris_kmd_backend.c',
  'iris_kmd_backend.h',
  'iris_measure.c',
  'iris_measure.h',
  'iris_monitor.c',
  'iris_perf.h',
  'iris_perf.c',
  'iris_performance_query.c',
  'iris_pipe.h',
  'iris_pipe_control.c',
  'iris_program.c',
  'iris_program_cache.c',
  'iris_resolve.c',
  'iris_resource.c',
  'iris_resource.h',
  'iris_screen.c',
  'iris_screen.h',
  'iris_disk_cache.c',
  'iris_utrace.c',
)

files_libiris_str = [
  'i915/iris_batch.c',
  'i915/iris_batch.h',
  'i915/iris_bufmgr.c',
  'i915/iris_bufmgr.h',
  'i915/iris_kmd_backend.c',
  'xe/iris_batch.c',
  'xe/iris_batch.h',
  'xe/iris_bufmgr.c',
  'xe/iris_bufmgr.h',
  'xe/iris_kmd_backend.c',
  'driinfo_iris.h',
  'iris_batch.c',
  'iris_batch.h',
  'iris_binder.c',
  'iris_binder.h',
  'iris_blit.c',
  'iris_border_color.c',
  'iris_bufmgr.c',
  'iris_bufmgr.h',
  'iris_clear.c',
  'iris_context.c',
  'iris_context.h',
  'iris_draw.c',
  'iris_fence.c',
  'iris_fence.h',
  'iris_fine_fence.c',
  'iris_fine_fence.h',
  'iris_formats.c',
  'iris_genx_macros.h',
  'iris_genx_protos.h',
  'iris_kmd_backend.c',
  'iris_kmd_backend.h',
  'iris_measure.c',
  'iris_measure.h',
  'iris_monitor.c',
  'iris_perf.h',
  'iris_perf.c',
  'iris_performance_query.c',
  'iris_pipe.h',
  'iris_pipe_control.c',
  'iris_program.c',
  'iris_program_cache.c',
  'iris_resolve.c',
  'iris_resource.c',
  'iris_resource.h',
  'iris_screen.c',
  'iris_screen.h',
  'iris_disk_cache.c',
  'iris_utrace.c',
]

iris_per_hw_ver_libs = []
foreach v : ['80', '90', '110', '120', '125', '200', '300']
  if v == '80' and not with_intel_elk
    continue
  endif

  iris_per_hw_ver_libs += static_library(
    'iris_per_hw_ver@0@'.format(v),
    ['iris_blorp.c', 'iris_query.c', 'iris_state.c', 'iris_indirect_gen.c', gen_xml_pack],
    include_directories : [inc_include, inc_src, inc_mapi, inc_mesa, inc_gallium, inc_gallium_aux, inc_intel],
    c_args : [
      intel_common_args,
      no_override_init_args, sse2_args,
      '-DGFX_VERx10=@0@'.format(v),
    ],
    gnu_symbol_visibility : 'hidden',
    dependencies : [dep_libdrm, dep_valgrind, idep_genxml, idep_nir_headers,
                    idep_intel_driver_ds_headers, idep_intel_shaders,
                    idep_intel_blorp, idep_mesautil],
  )
endforeach

libiris = static_library(
  'iris',
  [files_libiris, gen_xml_pack],
  include_directories : [
    inc_src, inc_include, inc_gallium, inc_gallium_aux, inc_intel,
    inc_gallium_drivers,
    # these should not be necessary, but main/macros.h...
    inc_mesa, inc_mapi
  ],
  c_args : [intel_common_args, sse2_args],
  cpp_args : [intel_common_args, sse2_args],
  gnu_symbol_visibility : 'hidden',
  dependencies : [dep_libdrm, dep_valgrind, idep_genxml, idep_nir_headers,
                  idep_libintel_common, idep_intel_driver_ds, idep_intel_dev,
                  idep_intel_blorp_elk, idep_intel_decoder_elk,
                  idep_intel_blorp, idep_intel_decoder_brw,
                  idep_intel_compiler_elk, idep_intel_compiler_brw,
                  idep_mesautil],
  link_with : [
    iris_per_hw_ver_libs, libisl,
    libintel_perf
  ],
)
dedup_files = []
seen = []

foreach f : files_libiris_str
  if not seen.contains(f)
    dedup_files += [f]
    seen += [f]
  endif
endforeach


foreach src : dedup_files

  if not src.endswith('.c')
    continue
  endif
  src_str = '@0@'.format(src)  
  src_name = src_str.split('/')[-1]  
  src_base = src_str.replace('/', '_').replace('.', '_') 
  target_name = src_base + '_ll'
  output_name = src_base.replace('.c', '.ll')
  
  ll = custom_target(
    target_name,
    input: src,
    output: output_name,
    build_by_default : true,
    command: ['/usr/local/bin/clang', 
    '-S', '-emit-llvm',  '-D_FILE_OFFSET_BITS=64',
    '-D__STDC_CONSTANT_MACROS',
    '-D__STDC_FORMAT_MACROS',
    '-D__STDC_LIMIT_MACROS',
    '-DPACKAGE_VERSION="25.2.0-devel"',
    '-DPACKAGE_BUGREPORT="https://gitlab.freedesktop.org/mesa/mesa/-/issues"',
    '-DHAVE_OPENGL=1',
    '-DHAVE_OPENGL_ES_1=1',
    '-DHAVE_OPENGL_ES_2=1',
    '-DHAVE_R300',
    '-DHAVE_R600',
    '@INPUT@',
    '-DHAVE_RADEONSI',
    '-DHAVE_NOUVEAU',
    '-DHAVE_VIRGL',
    '-DHAVE_SVGA',
    '-DHAVE_LLVMPIPE',
    '-DHAVE_SOFTPIPE',
    '-DHAVE_IRIS',
    '-DHAVE_CROCUS',
    '-DHAVE_I915',
    '-DHAVE_ZINK',
    '-DHAVE_SWRAST',
    '-DVIDEO_CODEC_VC1DEC=0',
    '-DVIDEO_CODEC_H264DEC=0',
    '-DVIDEO_CODEC_H264ENC=0',
    '-DVIDEO_CODEC_H265DEC=0',
    '-DVIDEO_CODEC_H265ENC=0',
    '-DVIDEO_CODEC_AV1DEC=1',
    '-DVIDEO_CODEC_AV1ENC=1',
    '-DVIDEO_CODEC_VP9DEC=1',
    '-DHAVE_X11_PLATFORM',
    '-DHAVE_WAYLAND_PLATFORM',
    '-DHAVE_SURFACELESS_PLATFORM',
    '-DHAVE_DRM_PLATFORM',
    '-DHAVE_XCB_PLATFORM',
    '-DUSE_LIBGLVND=1',
    '-DHAVE_ST_VDPAU',
    '-DHAVE_VA_SURFACE_ATTRIB_DRM_FORMAT_MODIFIERS',
    '-DGLX_INDIRECT_RENDERING',
    '-DGLX_DIRECT_RENDERING',
    '-DGLX_USE_DRM',
    '-DGLAPI_EXPORT_PROTO_ENTRY_POINTS=0',
    '-DALLOW_KCMP',
    '-DMESA_DEBUG=1',
    '-DENABLE_SHADER_CACHE',
    '-DHAVE___BUILTIN_BSWAP32',
    '-DHAVE___BUILTIN_BSWAP64',
    '-DHAVE___BUILTIN_CLZ',
    '-DHAVE___BUILTIN_CLZLL',
    '-DHAVE___BUILTIN_CTZ',
    '-DHAVE___BUILTIN_EXPECT',
    '-DHAVE___BUILTIN_FFS',
    '-DHAVE___BUILTIN_FFSLL',
    '-DHAVE___BUILTIN_POPCOUNT',
    '-DHAVE___BUILTIN_POPCOUNTLL',
    '-DHAVE___BUILTIN_UNREACHABLE',
    '-DHAVE___BUILTIN_TYPES_COMPATIBLE_P',
    '-DHAVE_FUNC_ATTRIBUTE_CONST',
    '-DHAVE_FUNC_ATTRIBUTE_FLATTEN',
    '-DHAVE_FUNC_ATTRIBUTE_MALLOC',
    '-DHAVE_FUNC_ATTRIBUTE_PURE',
    '-DHAVE_FUNC_ATTRIBUTE_UNUSED',
    '-DHAVE_FUNC_ATTRIBUTE_WARN_UNUSED_RESULT',
    '-DHAVE_FUNC_ATTRIBUTE_WEAK',
    '-DHAVE_FUNC_ATTRIBUTE_FORMAT',
    '-DHAVE_FUNC_ATTRIBUTE_PACKED',
    '-DHAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL',
    '-DHAVE_FUNC_ATTRIBUTE_ALIAS',
    '-DHAVE_FUNC_ATTRIBUTE_NORETURN',
    '-DHAVE_FUNC_ATTRIBUTE_VISIBILITY',
    '-DHAVE_UINT128',
    '-DHAVE_REALLOCARRAY',
    '-DHAVE_FMEMOPEN',
    '-D_GNU_SOURCE',
    '-DUSE_SSE41',
    '-DHAVE___BUILTIN_IA32_CLFLUSHOPT',
    '-DUSE_GCC_ATOMIC_BUILTINS',
    '-DUSE_X86_64_ASM',
    '-DMAJOR_IN_SYSMACROS',
    '-DHAS_SCHED_H',
    '-DHAS_SCHED_GETAFFINITY',
    '-DHAVE_LINUX_FUTEX_H',
    '-DHAVE_ENDIAN_H',
    '-DHAVE_DLFCN_H',
    '-DHAVE_SYS_SHM_H',
    '-DHAVE_CET_H',
    '-DHAVE_SYS_INOTIFY_H',
    '-DHAVE_LINUX_UDMABUF_H',
    '-DHAVE_STRTOF',
    '-DHAVE_MKOSTEMP',
    '-DHAVE_MEMFD_CREATE',
    '-DHAVE_RANDOM_R',
    '-DHAVE_FLOCK',
    '-DHAVE_STRTOK_R',
    '-DHAVE_GETRANDOM',
    '-DHAVE_POSIX_FALLOCATE',
    '-DHAVE_SECURE_GETENV',
    '-DHAVE_GNU_QSORT_R',
    '-DHAVE_STRUCT_TIMESPEC',
    '-DHAVE_PROGRAM_INVOCATION_NAME',
    '-DHAVE_ISSIGNALING',
    '-DHAVE_POSIX_MEMALIGN',
    '-DHAVE_DIRENT_D_TYPE',
    '-DHAVE_STRTOD_L',
    '-DHAVE_DLADDR',
    '-DHAVE_DL_ITERATE_PHDR',
    '-DSUPPORT_INTEL_INTEGRATED_GPUS',
    '-DHAVE_ZLIB',
    '-DHAVE_ZSTD',
    '-DHAVE_COMPRESSION',
    '-DHAVE_PTHREAD',
    '-DHAVE_PTHREAD_SETAFFINITY',
    '-DHAVE_LIBDRM',
    '-DHAVE_LIBUDEV',
    '-DMESA_LLVM_VERSION_STRING="21.0.0"',
    '-DLLVM_IS_SHARED=1',
    '-DLLVM_AVAILABLE=1',
    '-DDRAW_LLVM_AVAILABLE=1',
    '-DAMD_LLVM_AVAILABLE=1',
    '-DGALLIVM_USE_ORCJIT=0',
    '-DHAVE_SPIRV_TOOLS',
    '-DUSE_LIBELF',
    '-DHAVE_VALGRIND',
    '-DTHREAD_SANITIZER=0',
    '-DHAVE_LIBUNWIND',
    '-DWL_HIDE_DEPRECATED',
    '-DHAVE_X11_DRM',
    '-DHAVE_DRI',
    '-DHAVE_DRI2',
    '-DHAVE_DRISW_KMS',
    '-DINTEL_USE_ELK','-Isrc/gallium/drivers/iris/libiris.a.p',
    '-Isrc/gallium/drivers/iris',
    '-I../src/gallium/drivers/iris',
    '-Isrc',
    '-I../src',
    '-Iinclude',
    '-I../include',
    '-I../src/gallium/include',
    '-Isrc/gallium/auxiliary',
    '-I../src/gallium/auxiliary',
    '-Isrc/intel',
    '-I../src/intel',
    '-Isrc/gallium/drivers',
    '-I../src/gallium/drivers',
    '-Isrc/mesa',
    '-I../src/mesa',
    '-Isrc/mapi',
    '-I../src/mapi',
    '-Isrc/intel/genxml',
    '-I../src/intel/genxml',
    '-Isrc/compiler/nir',
    '-I../src/compiler/nir',
    '-Isrc/compiler',
    '-I../src/compiler',
    '-Isrc/util/format',
    '-Isrc/intel/ds',
    '-Isrc/intel/dev',
    '-Isrc/compiler/spirv',
    '-I/usr/include/libdrm',
    '-I/usr/include/valgrind',
    '-I/usr/include/x86_64-linux-gnu',
    '-I/usr/local/include']
  )
  
endforeach
driver_iris = declare_dependency(
  compile_args : '-DGALLIUM_IRIS',
  link_with : [libiris, libiriswinsys],
)
