# Copyright © 2017 Intel Corporation
# SPDX-License-Identifier: MIT

files_i915 = files(
  'i915_batchbuffer.h',
  'i915_batch.h',
  'i915_blit.c',
  'i915_blit.h',
  'i915_clear.c',
  'i915_context.c',
  'i915_context.h',
  'i915_debug.c',
  'i915_debug_fp.c',
  'i915_debug.h',
  'i915_debug_private.h',
  'i915_flush.c',
  'i915_fpc_emit.c',
  'i915_fpc.h',
  'i915_fpc_optimize.c',
  'i915_fpc_translate.c',
  'i915_prim_emit.c',
  'i915_prim_vbuf.c',
  'i915_public.h',
  'i915_query.c',
  'i915_query.h',
  'i915_reg.h',
  'i915_resource_buffer.c',
  'i915_resource.c',
  'i915_resource.h',
  'i915_resource_texture.c',
  'i915_screen.c',
  'i915_screen.h',
  'i915_state.c',
  'i915_state_derived.c',
  'i915_state_dynamic.c',
  'i915_state_emit.c',
  'i915_state_fpc.c',
  'i915_state.h',
  'i915_state_immediate.c',
  'i915_state_inlines.h',
  'i915_state_sampler.c',
  'i915_state_static.c',
  'i915_surface.c',
  'i915_surface.h',
  'i915_winsys.h',
)

files_i915_str = [
  'i915_batchbuffer.h',
  'i915_batch.h',
  'i915_blit.c',
  'i915_blit.h',
  'i915_clear.c',
  'i915_context.c',
  'i915_context.h',
  'i915_debug.c',
  'i915_debug_fp.c',
  'i915_debug.h',
  'i915_debug_private.h',
  'i915_flush.c',
  'i915_fpc_emit.c',
  'i915_fpc.h',
  'i915_fpc_optimize.c',
  'i915_fpc_translate.c',
  'i915_prim_emit.c',
  'i915_prim_vbuf.c',
  'i915_public.h',
  'i915_query.c',
  'i915_query.h',
  'i915_reg.h',
  'i915_resource_buffer.c',
  'i915_resource.c',
  'i915_resource.h',
  'i915_resource_texture.c',
  'i915_screen.c',
  'i915_screen.h',
  'i915_state.c',
  'i915_state_derived.c',
  'i915_state_dynamic.c',
  'i915_state_emit.c',
  'i915_state_fpc.c',
  'i915_state.h',
  'i915_state_immediate.c',
  'i915_state_inlines.h',
  'i915_state_sampler.c',
  'i915_state_static.c',
  'i915_surface.c',
  'i915_surface.h',
  'i915_winsys.h',
]

dedup_files = []
seen = []

foreach f : files_i915_str
  if not seen.contains(f)
    dedup_files += [f]
    seen += [f]
  endif
endforeach

libi915 = static_library(
  'i915',
  files_i915,
  gnu_symbol_visibility : 'hidden',
  include_directories : [inc_include, inc_src, inc_gallium, inc_gallium_aux],
  c_args : ['-v'],
  cpp_args : ['-v'],
  dependencies : [idep_nir, idep_mesautil],
)


foreach src : dedup_files

  if not src.endswith('.c')
    continue
  endif
  src_str = '@0@'.format(src)  
  src_name = src_str.split('/')[-1]  
  src_base = src_str.replace('/', '_').replace('.', '_') 
  target_name = src_base + '_ll'
  output_name = src_base.replace('.c', '.ll')
  
  ll = custom_target(
    target_name,
    input: src,
    output: output_name,
    build_by_default: true,
    command: [
      '/usr/local/bin/clang', '-S', '-emit-llvm',
      '@INPUT@',
  '-Isrc/gallium/drivers/i915/libi915.a.p',
  '-Isrc/gallium/drivers/i915',
  '-I../src/gallium/drivers/i915',
  '-Iinclude',
  '-I../include',
  '-Isrc',
  '-I../src',
  '-I../src/gallium/include',
  '-Isrc/gallium/auxiliary',
  '-I../src/gallium/auxiliary',
  '-Isrc/compiler/nir',
  '-I../src/compiler/nir',
  '-Isrc/compiler',
  '-I../src/compiler',
  '-Isrc/util/format',
  '-I/usr/include/valgrind',
  '-I/usr/include/x86_64-linux-gnu',
  '-I/usr/include/libdrm',
 '-D_FILE_OFFSET_BITS=64',
  '-D__STDC_CONSTANT_MACROS',
  '-D__STDC_FORMAT_MACROS',
  '-D__STDC_LIMIT_MACROS',
  '-DPACKAGE_VERSION=25.2.0-devel',
  '-DPACKAGE_BUGREPORT=https://gitlab.freedesktop.org/mesa/mesa/-/issues',
  '-DHAVE_OPENGL=1',
  '-DHAVE_OPENGL_ES_1=1',
  '-DHAVE_OPENGL_ES_2=1',
  '-DHAVE_R300',
  '-DHAVE_R600',
  '-DHAVE_RADEONSI',
  '-DHAVE_NOUVEAU',
  '-DHAVE_VIRGL',
  '-DHAVE_SVGA',
  '-DHAVE_LLVMPIPE',
  '-DHAVE_SOFTPIPE',
  '-DHAVE_IRIS',
  '-DHAVE_CROCUS',
  '-DHAVE_I915',
  '-DHAVE_ZINK',
  '-DHAVE_SWRAST',
  '-DVIDEO_CODEC_VC1DEC=0',
  '-DVIDEO_CODEC_H264DEC=0',
  '-DVIDEO_CODEC_H264ENC=0',
  '-DVIDEO_CODEC_H265DEC=0',
  '-DVIDEO_CODEC_H265ENC=0',
  '-DVIDEO_CODEC_AV1DEC=1',
  '-DVIDEO_CODEC_AV1ENC=1',
  '-DVIDEO_CODEC_VP9DEC=1',
  '-DHAVE_X11_PLATFORM',
  '-DHAVE_WAYLAND_PLATFORM',
  '-DHAVE_SURFACELESS_PLATFORM',
  '-DHAVE_DRM_PLATFORM',
  '-DHAVE_XCB_PLATFORM',
  '-DUSE_LIBGLVND=1',
  '-DHAVE_ST_VDPAU',
  '-DHAVE_VA_SURFACE_ATTRIB_DRM_FORMAT_MODIFIERS',
  '-DGLX_INDIRECT_RENDERING',
  '-DGLX_DIRECT_RENDERING',
  '-DGLX_USE_DRM',
  '-DGLAPI_EXPORT_PROTO_ENTRY_POINTS=0',
  '-DALLOW_KCMP',
  '-DMESA_DEBUG=1',
  '-DENABLE_SHADER_CACHE',
  '-DHAVE___BUILTIN_BSWAP32',
  '-DHAVE___BUILTIN_BSWAP64',
  '-DHAVE___BUILTIN_CLZ',
  '-DHAVE___BUILTIN_CLZLL',
  '-DHAVE___BUILTIN_CTZ',
  '-DHAVE___BUILTIN_EXPECT',
  '-DHAVE___BUILTIN_FFS',
  '-DHAVE___BUILTIN_FFSLL',
  '-DHAVE___BUILTIN_POPCOUNT',
  '-DHAVE___BUILTIN_POPCOUNTLL',
  '-DHAVE___BUILTIN_UNREACHABLE',
  '-DHAVE___BUILTIN_TYPES_COMPATIBLE_P',
  '-DHAVE_FUNC_ATTRIBUTE_CONST',
  '-DHAVE_FUNC_ATTRIBUTE_FLATTEN',
  '-DHAVE_FUNC_ATTRIBUTE_MALLOC',
  '-DHAVE_FUNC_ATTRIBUTE_PURE',
  '-DHAVE_FUNC_ATTRIBUTE_UNUSED',
  '-DHAVE_FUNC_ATTRIBUTE_WARN_UNUSED_RESULT',
  '-DHAVE_FUNC_ATTRIBUTE_WEAK',
  '-DHAVE_FUNC_ATTRIBUTE_FORMAT',
  '-DHAVE_FUNC_ATTRIBUTE_PACKED',
  '-DHAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL',
  '-DHAVE_FUNC_ATTRIBUTE_ALIAS',
  '-DHAVE_FUNC_ATTRIBUTE_NORETURN',
  '-DHAVE_FUNC_ATTRIBUTE_VISIBILITY',
  '-DHAVE_UINT128',
  '-DHAVE_REALLOCARRAY',
  '-DHAVE_FMEMOPEN',
  '-D_GNU_SOURCE',
  '-DUSE_SSE41',
  '-DHAVE___BUILTIN_IA32_CLFLUSHOPT',
  '-DUSE_GCC_ATOMIC_BUILTINS',
  '-DUSE_X86_64_ASM',
  '-DMAJOR_IN_SYSMACROS',
  '-DHAS_SCHED_H',
  '-DHAS_SCHED_GETAFFINITY',
  '-DHAVE_LINUX_FUTEX_H',
  '-DHAVE_ENDIAN_H',
  '-DHAVE_DLFCN_H',
  '-DHAVE_SYS_SHM_H',
  '-DHAVE_CET_H',
  '-DHAVE_SYS_INOTIFY_H',
  '-DHAVE_LINUX_UDMABUF_H',
  '-DHAVE_STRTOF',
  '-DHAVE_MKOSTEMP',
  '-DHAVE_MEMFD_CREATE',
  '-DHAVE_RANDOM_R',
  '-DHAVE_FLOCK',
  '-DHAVE_STRTOK_R',
  '-DHAVE_GETRANDOM',
  '-DHAVE_POSIX_FALLOCATE',
  '-DHAVE_SECURE_GETENV',
  '-DHAVE_GNU_QSORT_R',
  '-DHAVE_STRUCT_TIMESPEC',
  '-DHAVE_PROGRAM_INVOCATION_NAME',
  '-DHAVE_ISSIGNALING',
  '-DHAVE_POSIX_MEMALIGN',
  '-DHAVE_DIRENT_D_TYPE',
  '-DHAVE_STRTOD_L',
  '-DHAVE_DLADDR',
  '-DHAVE_DL_ITERATE_PHDR',
  '-DSUPPORT_INTEL_INTEGRATED_GPUS',
  '-DHAVE_ZLIB',
  '-DHAVE_ZSTD',
  '-DHAVE_COMPRESSION',
  '-DHAVE_PTHREAD',
  '-DHAVE_PTHREAD_SETAFFINITY',
  '-DHAVE_LIBDRM',
  '-DHAVE_LIBUDEV',
  '-DMESA_LLVM_VERSION_STRING=21.0.0',
  '-DLLVM_IS_SHARED=1',
  '-DLLVM_AVAILABLE=1',
  '-DDRAW_LLVM_AVAILABLE=1',
  '-DAMD_LLVM_AVAILABLE=1',
  '-DGALLIVM_USE_ORCJIT=0',
  '-DHAVE_SPIRV_TOOLS',
  '-DUSE_LIBELF',
  '-DHAVE_VALGRIND',
  '-DTHREAD_SANITIZER=0',
  '-DHAVE_LIBUNWIND',
  '-DWL_HIDE_DEPRECATED',
  '-DHAVE_X11_DRM',
  '-DHAVE_DRI',
  '-DHAVE_DRI2',
  '-DHAVE_DRISW_KMS',
    ]
  )
endforeach
driver_i915 = declare_dependency(
  compile_args : '-DGALLIUM_I915',
  link_with : [libi915, libi915drm],
)
